name: alphinance
description: ""

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 25.01.29+2

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  csv: ^6.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  get: ^4.6.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
